font_family IosevkaTerm NF
font_size 14

background_opacity 0.75
background_blur 20

background #06080f
foreground #f3f6f9
cursor #e0c15a
selection_background #263356
selection_foreground #f3f6f9

color0 #06080f
color1 #cb7c94
color2 #b7cc85
color3 #ffe066
color4 #7fb4ca
color5 #ff8dd7
color6 #7aa89f
color7 #f3f6f9
color8 #8a8fa3
color9 #de8fa8
color10 #d1e8a9
color11 #fff7b1
color12 #a3d4d5
color13 #ffaeea
color14 #7fb4ca
color15 #f3f6f9

tab_bar_style powerline
shell fish
