foreground              #d1d1d1
background              #030107
selection_foreground    #030107
selection_background    #a77ef5
cursor                  #d1d1d1
cursor_text_color       #030107
url_color               #a77ef5
active_border_color     #a77ef5
inactive_border_color   #a6d1d1d1
bell_border_color       #a77ef5
active_tab_foreground   #030107
active_tab_background   #a77ef5
inactive_tab_foreground #d1d1d1
inactive_tab_background #030107
tab_bar_background      #030107
color0  #a6d1d1d1
color8  #a6d1d1d1
color1  #a77ef5
color9  #a77ef5
color2  #a77ef5
color10 #a77ef5
color3  #a77ef5
color11 #a77ef5
color4  #a77ef5
color12 #a77ef5
color5  #a77ef5
color13 #a77ef5
color6  #a77ef5
color14 #a77ef5
color7  #d1d1d1
color15 #d1d1d1
color16 #0d0b11
